# Generated by Django 3.1.2 on 2020-10-24 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bankwire',
            field=models.CharField(blank=True, default=0, max_length=54, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='egopay',
            field=models.CharField(blank=True, default=0, max_length=54, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hdmoney',
            field=models.CharField(blank=True, default=0, max_length=54, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='okpay',
            field=models.CharField(blank=True, default=0, max_length=54, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='paypal',
            field=models.CharField(blank=True, default=0, max_length=54, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='payza',
            field=models.CharField(blank=True, default=0, max_length=54, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='perfectmoney',
            field=models.CharField(blank=True, default=0, max_length=54, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pexpay',
            field=models.CharField(blank=True, default=0, max_length=54, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='solidtrustpay',
            field=models.CharField(blank=True, default=0, max_length=54, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='webmoney',
            field=models.CharField(blank=True, default=0, max_length=54, null=True),
        ),
    ]
