# Generated by Django 3.1.2 on 2020-10-24 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20201024_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ethereum',
            field=models.CharField(blank=True, default=0, max_length=15, null=True),
        ),
    ]
