# Generated by Django 3.1.2 on 2020-10-24 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_profile_ethereum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bankwire',
            field=models.FloatField(blank=True, default=0, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bitcoin',
            field=models.FloatField(blank=True, default=0, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='egopay',
            field=models.FloatField(blank=True, default=0, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ethereum',
            field=models.FloatField(blank=True, default=0, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hdmoney',
            field=models.FloatField(blank=True, default=0, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='okpay',
            field=models.FloatField(blank=True, default=0, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='paypal',
            field=models.FloatField(blank=True, default=0, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='payza',
            field=models.FloatField(blank=True, default=0, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='perfectmoney',
            field=models.FloatField(blank=True, default=0, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pexpay',
            field=models.FloatField(blank=True, default=0, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pin',
            field=models.FloatField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='solidtrustpay',
            field=models.FloatField(blank=True, default=0, max_length=54, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='webmoney',
            field=models.FloatField(blank=True, default=0, max_length=15, null=True),
        ),
    ]
