# Generated by Django 3.1.3 on 2020-11-17 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20201115_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bitcoin',
            field=models.DecimalField(blank=True, decimal_places=10, default=0.0, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ethereum',
            field=models.DecimalField(blank=True, decimal_places=10, default=0.0, max_digits=50, null=True),
        ),
    ]
