# Generated by Django 3.1.3 on 2020-11-17 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20201117_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminFact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_members', models.CharField(max_length=10)),
                ('total_deposits', models.CharField(max_length=10)),
                ('total_withdraw', models.CharField(max_length=10)),
                ('days_online', models.CharField(max_length=10)),
                ('registered_users', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='bitcoin',
            field=models.FloatField(blank=True, default=0, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ethereum',
            field=models.FloatField(blank=True, default=0, max_length=15, null=True),
        ),
    ]
