# Generated by Django 3.1.2 on 2020-10-31 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import finance.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('transaction_id', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=35, null=True)),
                ('amount', models.FloatField(max_length=15)),
                ('payment_mode', models.CharField(default='paypal', max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('subject', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=50)),
                ('status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment_Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.FloatField(max_length=15)),
                ('payment_mode', models.CharField(default='paypal', max_length=30)),
                ('account_id', models.CharField(max_length=125)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Deposit_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=25, unique=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('mature_date', models.DateTimeField(default=finance.models.seven_days_hence)),
                ('amount', models.FloatField(max_length=15)),
                ('currency', models.CharField(default='dollar', max_length=15)),
                ('plan', models.CharField(max_length=30)),
                ('payment_mode', models.CharField(default='paypal', max_length=30)),
                ('status', models.BooleanField(default=False)),
                ('matured', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=25, unique=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('mature_date', models.DateTimeField(default=finance.models.seven_days_hence)),
                ('amount', models.FloatField(max_length=15)),
                ('currency', models.CharField(default='dollar', max_length=15)),
                ('plan', models.CharField(max_length=30)),
                ('payment_mode', models.CharField(default='paypal', max_length=30)),
                ('status', models.BooleanField(default=False)),
                ('matured', models.BooleanField(default=False)),
                ('active_deposit', models.FloatField(blank=True, default=0.0, max_length=15, null=True)),
                ('mature_deposit', models.FloatField(blank=True, default=0.0, max_length=15, null=True)),
                ('total_payout', models.FloatField(blank=True, default=0.0, max_length=15, null=True)),
                ('pending_payout', models.FloatField(blank=True, default=0.0, max_length=15, null=True)),
                ('interest_today', models.FloatField(blank=True, default=0.0, max_length=15, null=True)),
                ('interest_earnings', models.FloatField(blank=True, default=0.0, max_length=15, null=True)),
                ('earning_today', models.FloatField(blank=True, default=0.0, max_length=15, null=True)),
                ('total_earning', models.FloatField(blank=True, default=0.0, max_length=15, null=True)),
                ('referral_interest', models.FloatField(blank=True, default=0.0, max_length=15, null=True)),
                ('referral', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
