# Generated by Django 3.1.2 on 2020-10-31 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import finance.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='D_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=25, unique=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('mature_date', models.DateTimeField(default=finance.models.seven_days_hence)),
                ('amount', models.FloatField(max_length=15)),
                ('currency', models.CharField(default='dollar', max_length=15)),
                ('plan', models.CharField(max_length=30)),
                ('payment_mode', models.CharField(default='paypal', max_length=30)),
                ('status', models.BooleanField(default=False)),
                ('matured', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Deposit_History',
        ),
    ]
