# Generated by Django 3.1.2 on 2020-10-31 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20201031_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='contact_no',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
