# Generated by Django 3.1.2 on 2020-11-01 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_tickets_contact_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_request',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
