# Generated by Django 3.1.2 on 2020-11-05 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_referral'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Referral',
        ),
    ]
