# Generated by Django 3.1.3 on 2020-11-15 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_auto_20201115_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='amount',
            field=models.FloatField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='currency',
            field=models.CharField(blank=True, default='dollar', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='payment_mode',
            field=models.CharField(blank=True, default='paypal', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='plan',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
