# Generated by Django 3.1.2 on 2020-11-08 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altcoininvest', '0002_blog_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.CharField(max_length=120)),
                ('comment', models.TextField()),
                ('approve', models.BooleanField(default=False)),
            ],
        ),
    ]
