# Generated by Django 3.1.2 on 2020-11-08 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altcoininvest', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='category',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
