# Generated by Django 3.1.2 on 2020-11-08 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altcoininvest', '0006_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='email',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
